# Load all *.zsh configuration scripts from ZSHD, in numerical sorting order.
# Unfortunately, this path doesn't use XDG_CONFIG_HOME, because directory
# structure is hardcoded in the file system of this dotfiles repository.
ZSH_RC_D="$HOME/.config/zsh/zshrc.d"
if [[ -d "$ZSH_RC_D" ]]; then
  # Suffix (rn) is a glob qualifier. (r) - readable; (n) - numeric sort order.
  # http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Qualifiers
  for script in "${ZSH_RC_D}"/**/*.zsh(rn); do
    # echo "hi, file $script"
    [[ -r "$script" ]] && source "$script"
  done
  unset script
fi
unset ZSH_RC_D

# Don't let exit code of configuration scripts slip into interactive mode.
true
