#!/bin/sh

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Old WebCam support
export LD_PRELOAD=/usr/lib/libv4l/v4l2convert.so

# https://wiki.archlinux.org/index.php/Xbindkeys
xbindkeys

exec startkde
